### Loading data into Pandas

In [28]:
import pandas as pd

#Set the option so the rows that we will see only 25 rows
pd.set_option('display.max_rows',25)
pokemon_data = pd.read_csv('pokemon_data.csv')

In [29]:
#to see the 5 first of the data
pokemon_data.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

### Reading Data in Pandas

In [30]:
len(pokemon_data)

800

In [31]:
pokemon_data.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

Note that the number of pokemon is 800, and every variable has the same number. So there is no missing value in this dataset

Let's see the column name

In [32]:
pokemon_data.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

We can see that there are 12 columns in the dataset.

In [33]:
#If we want to see the data of specific column/columns
pokemon_data[['#', 'Name', 'HP']]

       #                       Name   HP
0      1                  Bulbasaur   45
1      2                    Ivysaur   60
2      3                   Venusaur   80
3      3      VenusaurMega Venusaur   80
4      4                 Charmander   39
5      5                 Charmeleon   58
6      6                  Charizard   78
7      6  CharizardMega Charizard X   78
8      6  CharizardMega Charizard Y   78
9      7                   Squirtle   44
10     8                  Wartortle   59
11     9                  Blastoise   79
..   ...                        ...  ...
788  712                   Bergmite   55
789  713                    Avalugg   95
790  714                     Noibat   40
791  715                    Noivern   85
792  716                    Xerneas  126
793  717                    Yveltal  126
794  718           Zygarde50% Forme  108
795  719                    Diancie   50
796  719        DiancieMega Diancie   50
797  720        HoopaHoopa Confined   80
798  720         HoopaHoopa Unbound   80
799  721                  Volcanion   80

[800 rows x 3 columns]

In [34]:
#we can also see it like by doing this
pokemon_data.Name

0                      Bulbasaur
1                        Ivysaur
2                       Venusaur
3          VenusaurMega Venusaur
4                     Charmander
5                     Charmeleon
6                      Charizard
7      CharizardMega Charizard X
8      CharizardMega Charizard Y
9                       Squirtle
10                     Wartortle
11                     Blastoise
                 ...
788                     Bergmite
789                      Avalugg
790                       Noibat
791                      Noivern
792                      Xerneas
793                      Yveltal
794             Zygarde50% Forme
795                      Diancie
796          DiancieMega Diancie
797          HoopaHoopa Confined
798           HoopaHoopa Unbound
799                    Volcanion
Name: Name, Length: 800, dtype: object

In [36]:
#Call specific Rows with index location
pokemon_data.iloc[[0,1,2]]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [37]:
#Call specific location in this case the name of the last list pokemon
pokemon_data.iloc[799, 1]

'Volcanion'

In [39]:
#Finding the pokemon that the type 1 is Grass
pokemon_data.loc[pokemon_data['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
110,102,Exeggcute,Grass,Psychic,60,40,80,60,45,40,1,False
111,103,Exeggutor,Grass,Psychic,95,95,85,125,65,55,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
609,549,Lilligant,Grass,NaN,70,60,75,110,75,90,5,False
617,556,Maractus,Grass,NaN,75,86,67,106,67,60,5,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False
658,597,Ferroseed,Grass,Steel,44,50,91,24,86,10,5,False
659,598,Ferrothorn,Grass,Steel,74,94,131,54,116,20,5,False
701,640,Virizion,Grass,Fighting,91,90,72,90,129,108,5,True
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [48]:
#Finding The pokemons that the type 1 is Grass and type 2 is Fighting
pokemon_data.loc[
    (pokemon_data['Type 1']=='Grass') & (pokemon_data['Type 2']=='Fighting')
]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
310,286,Breloom,Grass,Fighting,60,130,80,60,60,70,3,False
701,640,Virizion,Grass,Fighting,91,90,72,90,129,108,5,True
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False

### Sorting Data

In [50]:
#Sorting by name
pokemon_data.sort_values('Name')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
286,263,Zigzagoon,Normal,NaN,38,30,41,30,41,60,3,False
707,644,Zekrom,Dragon,Electric,100,150,120,120,100,90,5,True
582,523,Zebstrika,Electric,NaN,75,100,63,80,63,116,5,False
157,145,Zapdos,Electric,Flying,90,90,85,125,90,100,1,True
367,335,Zangoose,Normal,NaN,73,115,60,60,60,90,3,False
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
332,306,Aggron,Steel,Rock,70,110,180,60,60,50,3,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
153,142,Aerodactyl,Rock,Flying,80,105,65,60,75,130,1,False
751,681,AegislashShield Forme,Steel,Ghost,60,50,150,50,150,60,6,False
750,681,AegislashBlade Forme,Steel,Ghost,60,150,50,150,50,60,6,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [51]:
#Sorting by name in descending order
pokemon_data.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
286,263,Zigzagoon,Normal,NaN,38,30,41,30,41,60,3,False
707,644,Zekrom,Dragon,Electric,100,150,120,120,100,90,5,True
582,523,Zebstrika,Electric,NaN,75,100,63,80,63,116,5,False
157,145,Zapdos,Electric,Flying,90,90,85,125,90,100,1,True
367,335,Zangoose,Normal,NaN,73,115,60,60,60,90,3,False
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
332,306,Aggron,Steel,Rock,70,110,180,60,60,50,3,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
153,142,Aerodactyl,Rock,Flying,80,105,65,60,75,130,1,False
751,681,AegislashShield Forme,Steel,Ghost,60,50,150,50,150,60,6,False
750,681,AegislashBlade Forme,Steel,Ghost,60,150,50,150,50,60,6,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [58]:
#Sorting more than one column
pokemon_data.sort_values(['Type 1', 'HP'], ascending=[False, False])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
185,171,Lanturn,Water,Electric,125,58,58,76,76,67,2,False
470,423,Gastrodon,Water,Ground,111,83,68,92,82,39,4,False
372,340,Whiscash,Water,Ground,110,78,73,76,71,60,3,False
597,537,Seismitoad,Water,Ground,105,95,75,85,75,74,5,False
199,184,Azumarill,Water,Fairy,100,50,80,60,80,50,2,False
264,245,Suicune,Water,NaN,100,75,115,90,115,85,2,True
282,260,Swampert,Water,Ground,100,110,90,85,90,60,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
307,283,Surskit,Bug,Water,40,30,32,50,52,65,3,False
457,412,Burmy,Bug,NaN,40,29,45,29,45,36,4,False
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False
732,664,Scatterbug,Bug,NaN,38,35,40,27,25,35,6,False
446,401,Kricketot,Bug,NaN,37,25,41,25,41,25,4,False
51,46,Paras,Bug,Grass,35,70,55,45,55,25,1,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

### Making Some Change To The DataFrame

In [60]:
pokemon_data['Total'] = pokemon_data['HP'] + pokemon_data['Attack'] + pokemon_data['Defense'] + pokemon_data['Sp. Atk'] + pokemon_data['Sp. Def'] + pokemon_data['Speed']

In [61]:
pokemon_data[0:5]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [67]:
#Changing the order of the columns
cols = list(pokemon_data.columns.values)
pokemon_data = pokemon_data[cols[0:10] + [cols[-1]] + cols[10:12]]

In [68]:
pokemon_data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,405,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,534,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,634,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,314,1,False
10,8,Wartortle,Water,NaN,59,63,80,65,80,58,405,1,False
11,9,Blastoise,Water,NaN,79,83,100,85,105,78,530,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,304,6,False
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,514,6,False
790,714,Noibat,Flying,Dragon,40,30,35,45,40,55,245,6,False
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,535,6,False
792,716,Xerneas,Fairy,NaN,126,131,95,131,98,99,680,6,True
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,680,6,True
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,600,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,600,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,700,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,600,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,680,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6,True

In [70]:
pokemon_data.to_csv('modified_pokemon_data.csv', index=False)

### Filtering Data

In [71]:
# so we can called the dataframe more easier :)
df = pokemon_data

In [72]:
#Let's say we want to find the type 1 fire and legendary pokemon
df.loc[(df['Type 1'] == 'Fire') & (df['Legendary'] == True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,580,1,True
263,244,Entei,Fire,NaN,115,115,85,90,75,100,580,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,680,2,True
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,600,4,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6,True

We could see that there are Type 1 = Fire which are also legendary pokemons

In [73]:
# Find Name that contain Mega
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,634,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,630,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,495,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,579,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,590,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,590,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,600,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,590,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,600,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,640,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,700,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,700,3,False
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,700,3,True
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,700,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,780,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,580,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,700,4,False
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,625,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,594,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,618,4,False
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,545,5,False
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,700,6,True

In [76]:
#Filtering using regular expressions
import re

df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,405,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,534,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,634,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,299,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,505,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,320,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,405,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,530,6,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,307,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,409,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,534,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,382,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,499,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,369,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,507,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,350,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,531,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6,True

In [80]:
df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,251,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,349,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,479,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,579,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,320,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,500,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,600,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,205,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,290,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,450,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,314,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,418,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,264,5,False

### Group By

In [85]:
df.groupby(['Type 1']).mean()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
Type 1,,,,,,,,,,
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,378.927536,3.217391,0.000000
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,445.741935,4.032258,0.064516
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,550.531250,3.875000,0.375000
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,443.409091,3.272727,0.090909
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,413.176471,4.117647,0.058824
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,416.444444,3.370370,0.000000
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,458.076923,3.211538,0.096154
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,485.000000,5.500000,0.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,439.562500,4.187500,0.062500
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,421.142857,3.357143,0.042857
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,437.500000,3.156250,0.125000
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,433.458333,3.541667,0.083333
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,401.683673,3.051020,0.020408
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,399.142857,2.535714,0.000000
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,475.947368,3.385965,0.245614
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,453.750000,3.454545,0.090909
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,487.703704,3.851852,0.148148
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,430.455357,2.857143,0.035714

In [86]:
df.groupby(['Type 1']).sum()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
Type 1,,,,,,,,,,
Bug,23080,3925,4897,4880,3717,4471,4256,26146,222,0.0
Dark,14302,2071,2740,2177,2314,2155,2361,13818,125,2.0
Dragon,15180,2666,3588,2764,3099,2843,2657,17617,124,12.0
Electric,15994,2631,3040,2917,3961,3243,3718,19510,144,4.0
Fairy,7642,1260,1046,1117,1335,1440,826,7024,70,1.0
Fighting,9824,1886,2613,1780,1434,1747,1784,11244,91,0.0
Fire,17025,3635,4408,3524,4627,3755,3871,23820,167,5.0
Flying,2711,283,315,265,377,290,410,1940,22,2.0
Ghost,15568,2062,2361,2598,2539,2447,2059,14066,134,2.0
Grass,24141,4709,5125,4956,5425,4930,4335,29480,235,3.0
Ground,11401,2361,3064,2715,1807,2008,2045,14000,101,4.0
Ice,10165,1728,1746,1714,1861,1831,1523,10403,85,2.0
Normal,31279,7573,7200,5865,5470,6245,7012,39365,299,2.0
Poison,7050,1883,2091,1927,1692,1803,1780,11176,71,0.0
Psychic,21706,4026,4073,3858,5609,4918,4645,27129,193,14.0
Rock,17280,2876,4086,4435,2787,3321,2460,19965,152,4.0
Steel,11957,1761,2503,3412,1823,2177,1492,13168,104,4.0
Water,33946,8071,8305,8170,8379,7898,7388,48211,320,4.0

In [90]:
df.groupby(['Type 1', 'Type 2']).count()

                  #  Name  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 2
Bug    Electric   2     2   2       2        2        2        2      2
       Fighting   2     2   2       2        2        2        2      2
       Fire       2     2   2       2        2        2        2      2
       Flying    14    14  14      14       14       14       14     14
       Ghost      1     1   1       1        1        1        1      1
       Grass      6     6   6       6        6        6        6      6
       Ground     2     2   2       2        2        2        2      2
       Poison    12    12  12      12       12       12       12     12
       Rock       3     3   3       3        3        3        3      3
       Steel      7     7   7       7        7        7        7      7
       Water      1     1   1       1        1        1        1      1
Dark   Dragon     3     3   3       3        3        3        3      3
...              ..   ...  ..     ...      ...      ...      ...    ...
Water  Electric   2     2   2       2        2        2        2      2
       Fairy      2     2   2       2        2        2        2      2
       Fighting   3     3   3       3        3        3        3      3
       Flying     7     7   7       7        7        7        7      7
       Ghost      2     2   2       2        2        2        2      2
       Grass      3     3   3       3        3        3        3      3
       Ground    10    10  10      10       10       10       10     10
       Ice        3     3   3       3        3        3        3      3
       Poison     3     3   3       3        3        3        3      3
       Psychic    5     5   5       5        5        5        5      5
       Rock       4     4   4       4        4        4        4      4
       Steel      1     1   1       1        1        1        1      1

                 Total  Generation  Legendary
Type 1 Type 2
Bug    Electric      2           2          2
       Fighting      2           2          2
       Fire          2           2          2
       Flying       14          14         14
       Ghost         1           1          1
       Grass         6           6          6
       Ground        2           2          2
       Poison       12          12         12
       Rock          3           3          3
       Steel         7           7          7
       Water         1           1          1
Dark   Dragon        3           3          3
...                ...         ...        ...
Water  Electric      2           2          2
       Fairy         2           2          2
       Fighting      3           3          3
       Flying        7           7          7
       Ghost         2           2          2
       Grass         3           3          3
       Ground       10          10         10
       Ice           3           3          3
       Poison        3           3          3
       Psychic       5           5          5
       Rock          4           4          4
       Steel         1           1          1

[136 rows x 11 columns]